language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script: yarn run build

after_success:
  - cd dist && zip -r ../indesign-scripts.zip . && cd ..
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --tags
  - node scripts/travis-after-success.js

branches:
  only:
    - master
